name: Pull Requests / Weekly QA

on:
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 0 * * 6"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # ratchet:actions/checkout@v7.0.1

      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # ratchet:actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Build
        run: go build -o awesome-docker ./cmd/awesome-docker

      - name: Build website
        run: ./awesome-docker build

      - name: Validate
        run: ./awesome-docker validate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
