name: Pull Requests / Weekly QA

on:
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 0 * * 6"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # ratchet:actions/checkout@v7.0.0

      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # ratchet:actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Build
        run: go build -o awesome-docker ./cmd/awesome-docker

      - name: Build website
        run: ./awesome-docker build

      - name: Validate
        run: ./awesome-docker validate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
